# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ed59b5b3226361edd66e2c19e5fd6d7f0d69d674b1d8e9f55962592b7bc8f942f3d5a6954d450ccf856e387d0f4d282606d98036857a761010f36511bd94a45

test:
  secret_key_base: 19ffe6a91e762742975be7a63962fd3583ab1387e17affea31365333e79152d2dff126f2f8d54e92419b557996639d2f10ad43f285c41ef673922d07c49b3e4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
